# Generated by Django 4.2.7 on 2023-11-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_categoria_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precio',
            new_name='Reseña',
        ),
    ]
