# Generated by Django 4.2.7 on 2023-11-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_precio_reseña'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Resenia',
        ),
    ]
