# Generated by Django 4.2.7 on 2023-11-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_reseña_resenia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resenia',
        ),
    ]
