# Generated by Django 4.2.7 on 2023-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_delete_resenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resenia', models.CharField(max_length=250)),
            ],
        ),
    ]
